axa/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('accueil', views.home, name='accueil'),
    path('login/', views.connexion, name='connexion'),
    path('logout', views.deconnexion, name='deconnexion'),
    path('signup', views.signup, name='signup'),
    path('home', views.home, name='home'),
    path('declare', views.declare, name='declare'),
    path('declareclient', views.declareclient, name='declareclient'),
]

axa/axa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('app.urls')),
]

axa/app/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models
from django.utils import timezone

# Create your models here.

class Litige(models.Model):
    fai = models.ForeignKey(User, on_delete=models.CASCADE)  # La liaison OneToOne vers le modèle User
    tempsdown = models.CharField(max_length=40)
    compensation = models.CharField(max_length=40)
    cause = models.CharField(max_length=400)
    entreprises_impactées = models.CharField(max_length=40, default="")
    creation_date = models.DateTimeField(default=timezone.now, 
                                verbose_name="Date de création")
    class Meta:
        verbose_name = "litige"
        ordering = ['creation_date']

    def __str__(self):
        return self.entreprises_impactées

class Client(models.Model):
    id_client = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=30)
    adresse = models.CharField(max_length=90)

    class Meta:
        verbose_name = "client"
        ordering = ['id_client']

    def __str__ (self):
        return self.name

axa/app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Litige
from .models import Client

class ConnexionForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, required=True, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

class Declare(forms.ModelForm):

    class Meta:
        model = Litige
        fields = ('fai','tempsdown','cause','compensation','entreprises_impactées')

class DeclareClient(forms.ModelForm):

    class Meta:
        model = Client
        fields = ('name','adresse')

axa/app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import Http404

from django.http import HttpResponse
from datetime import datetime

from .forms import ConnexionForm
from .forms import SignUpForm
from .forms import Declare
from .forms import DeclareClient

from .models import Litige
from .models import Client

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
import requests

# Create your views here.


def connexion(request):
    # Construire le formulaire, soit avec les données postées,
    # soit vide si l'utilisateur accède pour la première fois
    # à la page.
    form = ConnexionForm(request.POST or None)
    # Nous vérifions que les données envoyées sont valides
    # Cette méthode renvoie False s'il n'y a pas de données 
    # dans le formulaire ou qu'il contient des erreurs.
    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)  # Nous vérifions si les données sont correctes
            if user:  # Si l'objet renvoyé n'est pas None
                login(request, user)  # nous connectons l'utilisateur
                user = request.user
                litiges = Litige.objects.filter(fai=user)
                return render(request, 'menu/home.html', {'litiges': litiges})
            else: # sinon une erreur sera affichée
                error = True
    else:
        form = ConnexionForm()
    
    # Quoiqu'il arrive, on affiche la page du formulaire.
    return render(request, 'connection/login.html', locals())

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()

            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return render(request, 'menu/home.html')
    else:
        form = SignUpForm()
    return render(request, 'signup/signup.html', {'form': form})

def home(request):
    user = request.user
    litiges = Litige.objects.filter(fai=user)
    return render(request, 'menu/home.html', {
        'litiges': litiges
        })

def deconnexion(request):
    logout(request)
    return render(request, 'connection/logout.html')

def declare(request):
    clients = Client.objects.all()
    user = request.user
    litiges = Litige.objects.filter(fai=user)

    form = Declare(request.POST)
    if form.is_valid():
            form.save()
            return render(request, 'menu/home.html', {
        'litiges': litiges
        })
    else:
        form = Declare()
    return render(request, 'menu/declare.html', {'form': form, 'clients': clients, 'date': datetime.now()})

def declareclient(request):
    user = request.user
    litiges = Litige.objects.filter(fai=user)

    form = DeclareClient(request.POST)
    if form.is_valid():
            form.save()
            return render(request, 'menu/home.html', {
        'litiges': litiges
        })
    else:
        form = DeclareClient()
    return render(request, 'menu/declareclient.html', {'form': form})

axa/app/templates/connection/login.html
{% load widget_tweaks %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
    <div class="row mt50">
		<div class="input-field col s6 offset-s3">
            <center>
                <img class="responsive-img img" style="width: 250px;" src="/static/pic/axa.png" />
                <h2 class="flow-text indigo-text darken-4 logo">Se connecter</h2>
                {% if error %}
                <p class="indigo-text darken-4"><strong>Utilisateur inconnu ou mauvais mot de passe.</strong></p>
                {% endif %}

			    <div class="input-field col s6 offset-s3">
                    <form method="post" action=".">
                        {% csrf_token %}						
					    <div>
                            <input type="text" name="username" placeholder="Nom d'utilisateur" maxlength="30" required id="id_username">
					    </div>
					    <div>
                           <input type="password" name="password" placeholder="Mot de passe" required id="id_password">
					    </div>
					    <div>
                            <button class="btn waves-effect indigo darken-4 btn-co" type="submit" name="action">Connexion</button>
                            <a class="btn waves-effect indigo darken-4 btn-co" href="{% url 'signup' %}">S'inscrire</a>
                        </div>
                    </form>
		        </div>
            </center>
        </div>
    </div>
</body>
</html>

axa/app/templates/connection/logout.html
{% extends "base.html" %}

{% block content %} 
<center>
    <div class="row mt50">
        <div class="input-field col s6 offset-s3">
            <img class="responsive-img img" style="width: 250px;" src="/static/pic/axa.png" />
            <h2 class="flow-text indigo-text darken-4 logo">Vous etez desormais déconnecté</h2>
            <h2 class="flow-text indigo-text darken-4 logo">Merci de votre visite et à bientot</h2>
        </div>
    </div>
</center>
{% endblock %}

axa/app/templates/menu/declare.html
{% extends 'base.html' %}

{% block content %}
<center>
<h2 class="flow-text indigo-text darken-4">Créer votre litige :</h2>
<div class="row mt50">
    <div class="col s6 offset-s3">
    <form method="POST" class="post-form">
    <h2 class="flow-text indigo-text darken-4">Declaration de litige de {{ user.username }}</h2>
    {% csrf_token %}

        <div class="row">
            <input style="display: none;" name="fai" value="{{ user.id }}" maxlength="10" required id="id_fai">
        </div>
        
        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="tempsdown" maxlength="40" required id="id_tempsdown">
                <label for="id_topic_lvl">Temps d'indisponibilité :</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="cause" maxlength="400" required id="id_cause">
                <label for="id_cause">Cause de la coupure :</label>
            </div>
        </div>

        <div class="row">        
            <div class="input-field col s12">
                <input type="text" name="compensation" maxlength="40" required id="id_compensation">
                <label for="id_topic_title">Montant de la compensation :</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <select type="text" name="entreprises_impactées" maxlength="50" required id="id_entreprises_impactées">
                    {% for client in clients %}
                    <option value ="{{ client.name }}">{{ client.name }}</option>
                    {% endfor %}
                </select> 
                <label for="id_entreprises_impactées">Quel client est impacté ? :</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
    		<button type="submit" class="btn btn-default indigo darken-4">Save</button>
            <a class="btn waves-effect indigo darken-4 btn-co" href="{% url 'home' %}">Annuler</a>	
        </div>
    </form>
    </div>
</div>
</center>

{% endblock %}

axa/app/templates/menu/declareclient.html
{% extends 'base.html' %}

{% block content %}
<center>
<h2 class="flow-text indigo-text darken-4">Créer un client :</h2>
<div class="row mt50">
    <div class="col s6 offset-s3">
    <form method="POST" class="post-form">
    {% csrf_token %}
        
        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="name" maxlength="40" required id="id_name">
                <label for="id_name">Nom du client :</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="adresse" maxlength="400" required id="id_adresse">
                <label for="id_adresse">Adresse du client :</label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
    		<button type="submit" class="btn btn-default indigo darken-4">Save</button>
            <a class="btn waves-effect indigo darken-4 btn-co" href="{% url 'home' %}">Annuler</a>	
        </div>
    </form>
    </div>
</div>
</center>

{% endblock %}

axa/app/templates/menu/home.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
    <h2 class="flow-text indigo-text darken-4">Bienvenue {{ user.first_name }} {{ user.last_name }} </h2>
    
    {% for litige in litiges %}
    <div class="row mt50">
    <div class="card col s10 offset-s1 ">
        <div class="card-content">
            <table class="table striped">
                <thead>
                    <tr>
                        <th>FAI</th>
                        <th>Temps d'indisponibilité</th>
                        <th>Cause</th>
                        <th>Compensation</th>
                        <th>Entreprise impactée</th>
                        <th>Date</th>
                    </tr>
                </thead>   
                <tbody>
                    <tr>
                        <td>{{ litige.fai }}</td>
                        <td>{{ litige.tempsdown }}</td>
                        <td>{{ litige.cause }}</td>
                        <td>{{ litige.compensation }}</td>
                        <td>{{ litige.entreprises_impactées }}</td>
                        <td>{{ litige.creation_date }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    </div>

    {% empty %}
    <div class="row mt50">
        <div class="card col s6 offset-s3 ">
            <div class="card-content">
                <h2 class="flow-text indigo-text darken-4">Vous n'avez aucun litige actuellement </h2>
            </div>
        </div>
    </div>

    {% endfor %}

    {% else %}
    <h2 class="flow-text indigo-text darken-4">Bienvenue, n'hesite pas à t'inscrire !</h2>
    {% endif %}
{% endblock %}

axa/app/templates/menu/profil.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
    <h2 class="flow-text red-text darken-2">Bienvenue {{ user.username }}</h2>
    <h2 class="flow-text red-text darken-2">Votre id de personnage est {{ profil.user.test }}</h2>
    <h2 class="flow-text red-text darken-2">Votre id de personnage est {{ user.profil.test }}</h2>
    <h2 class="flow-text red-text darken-2">Votre id de personnage est {{ profil.test }}</h2>
    <h2 class="flow-text red-text darken-2">Votre id de personnage est {{ user.test }}</h2>

    <h2 class="flow-text red-text darken-2">Profil.user {{ profil }}</h2>



    <h2 class="flow-text red-text darken-2">email {{ user.email }}</h2>
    {% else %}
    <h2 class="flow-text red-text darken-2">Bienvenue, n'hesite pas à t'inscrire !</h2>
    {% endif %}
{% endblock %}

axa/app/templates/signup/signup.html
{% load widget_tweaks %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
    <div class="row mt50">
		<div class="input-field col s6 offset-s3">
            <center>
                <img class="responsive-img img" style="width: 250px;" src="/static/pic/axa.png" />
                <h2 class="flow-text indigo-text darken-4 logo">S'inscrire</h2>

			    <div class="col s6 offset-s3">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <p>
                            <input id="ID3" type="{{ field.field.widget.input_type }}" name="{{ field.name }}" placeholder="{{ field.label }}">
                            {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                            {% endfor %}
                            </p>
                            {% endfor %}
                            
                            <button class="btn waves-effect indigo darken-4 btn-co" type="submit" name="action">Confirmer</button>
                            <a class="btn waves-effect indigo darken-4 btn-co" href="{% url 'connexion' %}">Se connecter</a>
                    </form>
		        </div>
            </center>
        </div>
    </div>
</body>
</html>

axa/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
{% block head %}
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="/static/css/materialize.css">
    <link rel="stylesheet" href="/static/css/custom.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">   
</head>
{% endblock %}

<body>

    {% if user.is_authenticated %}
    <nav>
        {% block nav %}
        <div class="nav-wrapper indigo darken-4">
            <a href="#" class="brand-logo right">AXA</a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="{% url 'home' %}">Mes Litiges</a></li>
                <li><a href="{% url 'declare' %}">Declarer un litige</a></li>
                <li><a href="{% url 'declareclient' %}">Declarer un client</a></li>
                <li><a href="{% url 'deconnexion' %}">Deconnexion</a></li>
            </ul>
        </div>
        {% endblock %}
    </nav>
    {% else %}
    <nav>
        {% block nav2 %}
        <div class="nav-wrapper indigo darken-4">
            <a href="#" class="brand-logo right">AXA</a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="{% url 'connexion' %}">Connexion</a></li>
            </ul>
        </div>
        {% endblock %}
    </nav>
    {% endif %}

    
    <div>
        {% block content %}
        {% endblock %}
    </div>
        
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
<script>
    $(document).ready(function(){
        $(".modal").modal();
		$('select').material_select();
    });      
</script>
</body>